### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by YAEH-IO** [nagyrajmund/gesticulating_agent_unity#1]
I'm trying to replicate the system but it says I don't have permission. It shows like below. How can I fix that? Thank you. 

```
$ git clone git@github.com:nagyrajmund/gesticulating_agent_unity.git
Cloning into 'gesticulating_agent_unity'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by nagyrajmund** [comment]
Hi,

This is likely a local issue with your SSH credentials, since the repo is public. Try `git clone https://github.com/nagyrajmund/gesticulating_agent_unity.git`, or set up your SSH credentials correctly as described [here](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh).
