### ISSUE TITLE
 c# code wrong in benderbot_demo branch

### ISSUE THREAD

**Issue by birdflies** [nagyrajmund/gesticulating_agent_unity#6]
Dear nagyrajmund,
when I unzip unity_source_code_blenderbot.zip.
I found the following problems: the c# code of the dialogue system is not blenderbot, but dialogflow.
This leads to the failure of calling the dialogue system in Unity. Would you like to help replace it with blenderbot?
Or if you have tried and successed, please help upload  c# code of blenderbot version. Thanks very much
![image](https://user-images.githubusercontent.com/8829984/130019536-c2ed9110-83ac-4a68-8c60-f306a0a312ac.png)

**Comment by nagyrajmund** [comment]
Hi @birdflies ,

It is indeed a bit confusing that the `DialogFlowCommunicator` files were not removed in the blenderbot version, but this should not cause an issue since they are not used at all. When you write a message into the text box in unity and click the `Submit` button, the following function is called:

```c#
private void _HandleTextInput(string inputText)
{
    Debug.Log("GesticulatingAgent::_HandleTextInput(string inputText) inputText: " + inputText);
    m_textScreen.text = "I'm thinking of a response, please wait...";
    
    m_AMQClient.SendTextToGesticulator(inputText);
}
```
which will simply send the text to the python client without contacting DialogFlow.

**Comment by nagyrajmund** [comment]
> This leads to the failure of calling the dialogue system in Unity. 

How does the communication fail, what error messages are you seeing?

**Comment by birdflies** [comment]
@nagyrajmund  Thanks ~ 
When you write a message into the text box in unity and click the Submit button, there is no problem.

But, When Click Talk to start recording speech input, and Stop to stop recording OR. It will use DialogFlow in GesticulatingAgent.cs. 
And the error messages is:
```
NullReferenceException: Object reference not set to an instance of an object
GesticulatingAgent+<_HandleAudioInput>d__12.MoveNext () (at Assets/Scripts/GesticulatingAgent.cs:119)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GesticulatingAgent:HandleUserAudioInput(String) (at Assets/Scripts/GesticulatingAgent.cs:78)
MicInput:RecordAudio() (at Assets/Scripts/MicInput.cs:98)
```


The error picture is as follow:
![image](https://user-images.githubusercontent.com/8829984/130073159-1f16c24a-9c5e-4707-9df8-3594c2598154.png)

**Comment by nagyrajmund** [comment]
Ah, I see! This is a limitation of the blenderbot version - speech recognition is not supported because that relies on Google ASR, which we can only access through DialogFlow in the codebase.

**Comment by birdflies** [comment]
@nagyrajmund  Maybe the reason is: When click the Stop button, the following function is called:
`private IEnumerator _HandleAudioInput(string inputAudio) 
    {
        Debug.Log("GesticulatingAgent::_HandleAudioInput(string inputAudio)");
        m_textScreen.text = "I'm thinking of a response, please wait...";

        // Create a request for DialogFlow to generate the agent's response
        UnityWebRequest webRequest = m_chatbot.CreateDialogFlowRequestFromAudio(inputAudio);

        // Send the request to DialogFlow and wait until the answer arrives
        yield return webRequest.SendWebRequest();

        ProcessDialogFlowResponse(webRequest);
    }`
I am not unfamiliar with C# and Unity. Would you like to help me solve this problem? Thank you very much. @nagyrajmund

**Comment by nagyrajmund** [comment]
This function is just leftover code from the DialogFlow version, where a web request, containing the recorded user speech, is sent to the DialogFlow platform which has speech recognition capabilities.

To add support for speech recognition in the blenderbot demo, we would have to interface with speech recognition software to get the text transcription of the user input. This should be possible with [the Google Speech-to-Text platform](https://cloud.google.com/speech-to-text), which you can use as a web service, or [Kaldi](https://kaldi-asr.org/), which is an offline toolkit, just to name a few examples.

Since I am not familiar with these tools, integrating them into the demos would sadly take more time for me than I can afford to spend on this project.

**Comment by birdflies** [comment]
> Ah, I see! This is a limitation of the blenderbot version - speech recognition is not supported because that relies on Google ASR, which we can only access through DialogFlow in the codebase.

Thanks, can you share a response

**Comment by birdflies** [comment]
Thanks
